sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=test-container

before_script:
  - docker build -t zabbix3.0-test .
  - docker run -d --name $TARGET_CONTAINER_ID zabbix3.0-test
  - sudo apt-get -y install python-pip
  - sudo pip install ansible
  - ansible-playbook ansible/sample.yml --extra-vars "container_name=$TARGET_CONTAINER_ID"
script:
  - bundle exec rspec
