- name: "Add container"
  hosts: localhost
  connection: local
  tasks:
    - name: run container
      docker:
        name: "{{ container_name }}"
        image: centos:latest
        docker_api_version: "1.20"
        pull: missing
        tty: yes
        privileged: yes
        command: /sbin/init
    - name: add host
      add_host: name={{ container_name }}
- hosts: "{{ container_name }}"
  connection: docker
  tasks:
  - name: install postfix
    yum: name=postfix state=installed
  - name: start postfix
    service: name=postfix state=started
